#!/bin/bash
#
# shell script to execute binary with LD_LIBRARY_PATH set
# to the lib directory next to the bin directory that holds
# the executable
#
appname=`basename $0`
dirname=`dirname $0`
if [ "${dirname:0:1}" != "/" ]; then
dirname=$PWD/$dirname
fi
echo "starting faudes application" $appname 
LD_LIBRARY_PATH=$dirname/../lib:$dirname/../lib/plugins/viotypes
export LD_LIBRARY_PATH
echo "using LD_LIBRARY_PATH" $LD_LIBRARY_PATH
echo "resolving dynamic libraries:"
ldd $dirname/../lib/$appname.bin 
echo "starting" $appname.bin 
$dirname/../lib/$appname.bin $*